// <auto-generated />
using System;
using GameFinder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameFinder.Data.Migrations
{
    [DbContext(typeof(GameFinderDbContext))]
    [Migration("20261006094102_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameFinder.Data.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int?>("GameModes")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("PlayerOptions")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A fantastic journey through the cold North of Tamriel, where dragons have awoken once more to spread chaos upon the world.",
                            Difficulty = 0,
                            GenreId = 1,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/1/15/The_Elder_Scrolls_V_Skyrim_cover.png?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original",
                            Name = "The Elder Scrolls V: Skyrim",
                            PlayerOptions = 0,
                            ReleaseDate = new DateOnly(2011, 11, 11)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Take upon the mantle of Witcher and play through the story of the legendary Geralt of Rivia, on his perilous quest through the Northern Realms to find his adopted daughter Ciri and stop the Wild Hunt, once and for all.",
                            Difficulty = 0,
                            GenreId = 1,
                            ImageUrl = "https://thumb.wikimedia.org/wikipedia/en/thumb/0/0c/Witcher_3_cover_art.jpg/250px-Witcher_3_cover_art.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
                            Name = "The Witcher 3: Wild Hunt",
                            PlayerOptions = 0,
                            ReleaseDate = new DateOnly(2015, 5, 19)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Death is all that awaits you, stranger. Yet, would you dare become a hero, and enter the hallowed world of Lordran? If so - prepare to die, hero.",
                            Difficulty = 4,
                            GameModes = 2,
                            GenreId = 1,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/8/8d/Dark_Souls_Cover_Art.jpg?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original",
                            Name = "Dark Souls",
                            PlayerOptions = 4,
                            ReleaseDate = new DateOnly(2012, 8, 24)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Assemble your crew, and jump into this space-faring adventure as you navigate various missions together as a unit.",
                            Difficulty = 3,
                            GameModes = 0,
                            GenreId = 2,
                            ImageUrl = "https://images.squarespace-cdn.com/content/v1/61a0b244de2c6f4f7fbc4108/c0e96d30-f186-4cc7-88db-b30b1b78c98f/JumpSpace_Wallpaper_4k.png",
                            Name = "Jump Space",
                            PlayerOptions = 3,
                            ReleaseDate = new DateOnly(2025, 9, 19)
                        },
                        new
                        {
                            Id = 5,
                            Description = "The world is in ruin, overrun by the very spawn of hell itself. But one man alone stands against the terror, to rip and tear until it is done.",
                            Difficulty = 0,
                            GameModes = 2,
                            GenreId = 2,
                            ImageUrl = "https://thumb.wikimedia.org/wikipedia/en/thumb/2/28/Doom_Cover.jpg/250px-Doom_Cover.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
                            Name = "Doom",
                            PlayerOptions = 4,
                            ReleaseDate = new DateOnly(2016, 5, 13)
                        },
                        new
                        {
                            Id = 6,
                            Description = "The classic competitive shooter, now with improved graphics and physics like never before. Enter the new era of Counter-Strike today, and prove that you're still worthy!",
                            Difficulty = 4,
                            GameModes = 1,
                            GenreId = 2,
                            ImageUrl = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/730/6328493f4cc4a8fb83e1149be1cac5a7823fe588/capsule_616x353.jpg?t=1789251637",
                            Name = "Counter-Strike 2",
                            PlayerOptions = 3,
                            ReleaseDate = new DateOnly(2023, 9, 27)
                        },
                        new
                        {
                            Id = 7,
                            Description = "Escape the Underworld(and your responsibilties) in this Godlike-Roguelike!",
                            Difficulty = 0,
                            GenreId = 3,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/c/cc/Hades_cover_art.jpg?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original",
                            Name = "Hades",
                            PlayerOptions = 0,
                            ReleaseDate = new DateOnly(2020, 9, 17)
                        },
                        new
                        {
                            Id = 8,
                            Description = "Live. Die. Repeat. Fight your way out, or die trying. Then do it again. Also, make sure to deposit your cells before dying or you will be very mad at yourself!",
                            Difficulty = 3,
                            GenreId = 3,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/1/1f/Dead_cells_cover_art.png?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original",
                            Name = "Dead Cells",
                            PlayerOptions = 0,
                            ReleaseDate = new DateOnly(2019, 8, 7)
                        },
                        new
                        {
                            Id = 9,
                            Description = "Help Isaac overcome his Mother's fury in the classic, groundbreaking, and still difficult-as-ever game.",
                            Difficulty = 4,
                            GenreId = 3,
                            ImageUrl = "https://thumb.wikimedia.org/wikipedia/en/thumb/f/fa/Binding_of_isaac_header.jpg/250px-Binding_of_isaac_header.jpg?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
                            Name = "Binding of Isaac",
                            PlayerOptions = 0,
                            ReleaseDate = new DateOnly(2011, 9, 28)
                        },
                        new
                        {
                            Id = 10,
                            Description = "An underwater adventure awaits in this unforgettable, and terrifying, survival game.",
                            Difficulty = 2,
                            GenreId = 4,
                            ImageUrl = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/264710/header.jpg?t=1777456112",
                            Name = "Subnautica",
                            PlayerOptions = 0,
                            ReleaseDate = new DateOnly(2018, 1, 23)
                        },
                        new
                        {
                            Id = 11,
                            Description = "Hail, warrior. Your time among the living has passed, but your duty has not. You are of Odyn's chosen, blessed with the task to help unite the Tenth World. Fulfill your destiny, brave warrior, and help banish the chaos.",
                            Difficulty = 3,
                            GameModes = 0,
                            GenreId = 4,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/7/77/Valheim_2021_logo.jpg?utm_source=en.wikipedia.org&utm_campaign=index&utm_content=original",
                            Name = "Valheim",
                            PlayerOptions = 4,
                            ReleaseDate = new DateOnly(2026, 9, 9)
                        },
                        new
                        {
                            Id = 12,
                            Description = "Survival. Crafting. Zombies. And also a lot of difficulty that glues it all together. This is the ultimate survival experience, but the question is - how long can YOU survive?",
                            Difficulty = 4,
                            GameModes = 0,
                            GenreId = 4,
                            ImageUrl = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/108600/header.jpg?t=1787740093",
                            Name = "Project Zomboid",
                            PlayerOptions = 4,
                            ReleaseDate = new DateOnly(2026, 9, 9)
                        },
                        new
                        {
                            Id = 13,
                            Description = "Experience the thrill of owning a powerwasher, and using it to clean the world of fiflth. The soothing sounds of the water are a bonus.",
                            Difficulty = 1,
                            GameModes = 0,
                            GenreId = 5,
                            ImageUrl = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1290000/0184e192ea58230dd82aa8aed8134be3ed8fc4c2/capsule_616x353.jpg?t=1780392261",
                            Name = "Powerwash Simulator",
                            PlayerOptions = 4,
                            ReleaseDate = new DateOnly(2026, 9, 9)
                        },
                        new
                        {
                            Id = 14,
                            Description = "First of all, no, it's not what you think it is. Second - SOMEONE has to clean-up after all those nosy adventurers wreaking havoc on the dungeon. And third, yes you can wear a maid outfit. Yes, even as a male goblin.",
                            Difficulty = 2,
                            GameModes = 0,
                            GenreId = 5,
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGN9aGZpAO7FsqFOOr1ZVSrTeExazop2kQQnVMwTO8-TTRJvtc4B8jTp3E&s=10",
                            Name = "Goblin Cleanup",
                            PlayerOptions = 4,
                            ReleaseDate = new DateOnly(2025, 9, 18)
                        },
                        new
                        {
                            Id = 15,
                            Description = "The original clean-up game, the one to inspire many others, and the one that is still hardest to play because someone just can't stop kicking down the blood-filled buckets. You know who you are.",
                            Difficulty = 4,
                            GameModes = 0,
                            GenreId = 5,
                            ImageUrl = "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/246900/header.jpg?t=1666984711",
                            Name = "Viscera Cleanup Detail",
                            PlayerOptions = 4,
                            ReleaseDate = new DateOnly(2015, 10, 23)
                        });
                });

            modelBuilder.Entity("GameFinder.Data.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Play through a story, complete quests, and grow stronger by earning experience points!",
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Experience the thrill of combat through gunplay - be it tactical, or fast-paced, the choice is yours.",
                            Name = "FPS"
                        },
                        new
                        {
                            Id = 3,
                            Description = "No run is the same - play through randomized level every time, choose a different weapon or skill, and make every run your own.",
                            Name = "Roguelike"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Think you can survive the harshnes of the world? Then put that to the task in these games that will test your will and your mettle.",
                            Name = "Survival"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Some people want action, combat, and guts to spill. And others want to clean up after those people, because to see an awful mess cleaned up completely is a reward in itself.",
                            Name = "Cleaning"
                        });
                });

            modelBuilder.Entity("GameFinder.Data.Models.Game", b =>
                {
                    b.HasOne("GameFinder.Data.Models.Genre", "Genre")
                        .WithMany("Games")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("GameFinder.Data.Models.Genre", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
